use_frameworks!

target 'ExampleFrameworkMobile' do
  platform :ios, '9.0'
  podspec :path => 'ExampleFramework.podspec'
end

target 'ExampleFrameworkMac' do
  platform :osx, '10.9'
  podspec :path => 'ExampleFramework.podspec'
end

target 'ExampleFrameworkTV' do
  platform :tvos, '9.0'
  podspec :path => 'ExampleFramework.podspec'
end

target 'ExampleFrameworkWatch' do
  platform :watchos, '2.0'
  podspec :path => 'ExampleFramework.podspec'
end

